In [91]:
pip install pandas

Requirement already satisfied: pandas in c:\users\kp6948\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (1.5.2)
Requirement already satisfied: numpy>=1.21.0 in c:\users\kp6948\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pandas) (1.24.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\kp6948\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\kp6948\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pandas) (2022.7.1)
Requirement already satisfied: six>=1.5 in c:\users\kp6948\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\kp6948\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [92]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\kp6948\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (3.0.10)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\kp6948\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: et-xmlfile in c:\users\kp6948\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from openpyxl) (1.1.0)

In [93]:
import pandas as pd
import numpy as np

In [94]:
df =pd.read_csv("C:\\Users\\kp6948\Documents\\thist\\corridas\\2731_Unificado_01_01_2023_20_03_2023.csv",encoding='latin-1')

In [ ]:

new_equipo = df['equipo'].str.split(pat=r" " ,expand=True  ,n=-1 ,regex=True ).fillna("")

new_equipo['concat'] = new_equipo[0] + "-" + new_equipo[1] + "-" + new_equipo[2] + "-" +new_equipo[3] + "-" +new_equipo[4]  

new_equipo['concat'].unique()
df['equipo'] = new_equipo['concat']

In [95]:
new_0 = df['mensajeRPA'].str.split(pat=r"[^\\]+(.........[0-9]A)" ,expand=True  ,n=-1 ,regex=True ).fillna("")
new_0[1]





df['ordenmensajeRPA'] = new_0[1]

In [96]:
new1 = df['crm'].str.split(pat=r"[^\\]+(.........[0-9]A)" ,expand=True ,n=-1 ,regex=True ).fillna("")
new1
df["ordencrm"]= new1[0]

In [97]:
new2 = df['comentarios'].str.split(pat=r"[^\\]+(.........[0-9]A)" ,expand=True  ,n=-1 ,regex=True ).fillna("")
# new2
df["ordencomentarios"]= new2[1]

In [98]:
df.head()

,increment_id,fecha_de_pago,hora_de_pago,status,tipo,numero_renovar,f_rpa,f_renovacion,idc,crm,...,referencia_evo,redes_sociales,apps_streaming,allow_esim,addons,store_pickup,store_address,uidv2,ordenmensajeRPA,ordencomentarios
0,ECO001184195,24/02/2023,00:22:51,Validada,RenovaciÃ³n,3.316710e+09,24/02/2023 00:42:09,14/03/2023,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.023460e+13,,
1,ECO001184228,24/02/2023,00:43:51,Validada,Pospago,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,si,NaN,NaN,NaN,5.565950e+13,3118421192A,3118421192A
2,ECO001184252,24/02/2023,03:15:18,Validada,RenovaciÃ³n,5.523991e+09,24/02/2023 03:22:07,25/02/2023,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.398160e+13,,
3,ECO001184300,24/02/2023,07:57:58,Completada,Pospago,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,si,NaN,NaN,NaN,2.758770e+13,,3118523716A
4,ECO001184312,24/02/2023,08:02:17,Validada,RenovaciÃ³n,5.518043e+09,24/02/2023 08:21:13,17/03/2023,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.805790e+13,,

In [99]:
df_2 = df[['ordencomentarios','ordenmensajeRPA']]

df_2['Col4'] = df[['ordencomentarios','ordenmensajeRPA']].apply(lambda x: ''.join(x.dropna()), axis=1)

C:\Users\kp6948\AppData\Local\Temp\ipykernel_2196\1165192477.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['Col4'] = df[['ordencomentarios','ordenmensajeRPA']].apply(lambda x: ''.join(x.dropna()), axis=1)

In [100]:
df_2

    ordencomentarios ordenmensajeRPA                    Col4
0
1        3118421192A     3118421192A  3118421192A3118421192A
2
3        3118523716A                             3118523716A
4
..               ...             ...                     ...
699
700
701
702
703

[704 rows x 3 columns]

In [101]:
df['ordenfinal'] = df_2['Col4'].str[-11:]
df['Origen'] = "Magento"
df['Fuente'] = "full_bd_unificado"
df['ComentarioDuplicadoECO'] = "No"

In [102]:
df.reset_index(drop=True)

,increment_id,fecha_de_pago,hora_de_pago,status,tipo,numero_renovar,f_rpa,f_renovacion,idc,crm,...,store_pickup,store_address,uidv2,ordenmensajeRPA,ordencomentarios,ordenfinal,Origen,Fuente,ComentarioDuplicadoECO,ordencrm
0,ECO001184195,24/02/2023,00:22:51,Validada,RenovaciÃ³n,3.316710e+09,24/02/2023 00:42:09,14/03/2023,NaN,notfound,...,NaN,NaN,5.023460e+13,,,,Magento,full_bd_unificado,No,notfound
1,ECO001184228,24/02/2023,00:43:51,Validada,Pospago,NaN,NaN,NaN,NaN,notfound,...,NaN,NaN,5.565950e+13,3118421192A,3118421192A,3118421192A,Magento,full_bd_unificado,No,notfound
2,ECO001184252,24/02/2023,03:15:18,Validada,RenovaciÃ³n,5.523991e+09,24/02/2023 03:22:07,25/02/2023,NaN,notfound,...,NaN,NaN,5.398160e+13,,,,Magento,full_bd_unificado,No,notfound
3,ECO001184300,24/02/2023,07:57:58,Completada,Pospago,NaN,NaN,NaN,NaN,notfound,...,NaN,NaN,2.758770e+13,,3118523716A,3118523716A,Magento,full_bd_unificado,No,notfound
4,ECO001184312,24/02/2023,08:02:17,Validada,RenovaciÃ³n,5.518043e+09,24/02/2023 08:21:13,17/03/2023,NaN,notfound,...,NaN,NaN,2.805790e+13,,,,Magento,full_bd_unificado,No,notfound
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,ECO001191197,26/02/2023,23:08:55,Validada,RenovaciÃ³n,5.566722e+09,26/02/2023 23:21:27,27/02/2023,NaN,notfound,...,NaN,NaN,2.036660e+13,,,,Magento,full_bd_unificado,No,notfound
700,ECO001191248,26/02/2023,23:28:26,Validada,RenovaciÃ³n,5.588050e+09,26/02/2023 23:41:15,28/02/2023,NaN,notfound,...,NaN,NaN,6.623320e+13,,,,Magento,full_bd_unificado,No,notfound
701,ECO001191254,26/02/2023,23:36:27,Pagada,Pospago,NaN,NaN,NaN,NaN,notfound,...,NaN,NaN,0.000000e+00,,,,Magento,full_bd_unificado,No,notfound
702,ECO001191266,26/02/2023,23:38:26,Validada,RenovaciÃ³n,5.525754e+09,26/02/2023 23:41:55,27/03/2023,NaN,notfound,...,NaN,NaN,7.094370e+13,,,,Magento,full_bd_unificado,No,notfound
703,ECO001191311,26/02/2023,23:56:45,Validada,RenovaciÃ³n,4.776486e+09,27/02/2023 00:01:33,27/02/2023,NaN,notfound,...,NaN,NaN,1.207680e+13,,,,Magento,full_bd_unificado,No,notfound

In [103]:
a_index= ['increment_id',
 'fecha_de_pago',
 'status',
 'tipo',
 'guest',
 'region_factura',
 'oferta',
 'paquete',
 'mesesservicio',
 'sku',
 'precio_equipo',
 'precio_plan',
 'qty_ordered',
 'activacion',
 'total_pedido',
 'payment_method',
 'brand',
 'crm',
 'Origen',
 'Fuente',
 'ComentarioDuplicadoECO',
 'ordenmensajeRPA',
 'ordencrm',
 'ordencomentarios',
 'ordenfinal',
 'allow_esim']
df = df[a_index]

df.reindex(columns=[a_index])


df.to_csv(r'C:\\Users\\kp6948\Documents\\thist\\corridas\\corrida_2023_upsets_febrero_bd_clean.csv')

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 704 entries, 0 to 703
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   increment_id            704 non-null    object
 1   fecha_de_pago           704 non-null    object
 2   status                  704 non-null    object
 3   tipo                    704 non-null    object
 4   guest                   704 non-null    object
 5   region_factura          704 non-null    object
 6   oferta                  704 non-null    object
 7   paquete                 701 non-null    object
 8   mesesservicio           693 non-null    object
 9   sku                     5 non-null      object
 10  precio_equipo           3 non-null      object
 11  precio_plan             69 non-null     object
 12  qty_ordered             704 non-null    int64
 13  activacion              69 non-null     float64
 14  total_pedido            704 non-null    object
 15  payment_method          704 non-null    object
 16  brand                   655 non-null    object
 17  crm                     704 non-null    object
 18  Origen                  704 non-null    object
 19  Fuente                  704 non-null    object
 20  ComentarioDuplicadoECO  704 non-null    object
 21  ordenmensajeRPA         704 non-null    object
 22  ordencrm                704 non-null    object
 23  ordencomentarios        704 non-null    object
 24  ordenfinal              704 non-null    object
 25  allow_esim              36 non-null     object
dtypes: float64(1), int64(1), object(24)
memory usage: 143.1+ KB

In [105]:
df_subido_head = pd.read_csv('C:\\Users\\kp6948\\Downloads\\df_axyys prueba sincols2.csv')
list(df_subido_head.columns.values)

['increment_id',
 'fecha_de_pago',
 'status',
 'tipo',
 'guest',
 'region_factura',
 'oferta',
 'paquete',
 'mesesservicio',
 'sku',
 'precio_equipo',
 'precio_plan',
 'qty_ordered',
 'activacion',
 'total_pedido',
 'payment_method',
 'brand',
 'crm',
 'Origen',
 'Fuente',
 'ComentarioDuplicadoECO',
 'ordenmensajeRPA',
 'ordencrm',
 'ordencomentarios',
 'ordenfinal',
 'allow_esim']